/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface ImageGallery {
      'color': string;
      'src': Array<any>;
    }
  }

  interface HTMLImageGalleryElement extends StencilComponents.ImageGallery, HTMLStencilElement {}

  var HTMLImageGalleryElement: {
    prototype: HTMLImageGalleryElement;
    new (): HTMLImageGalleryElement;
  };
  interface HTMLElementTagNameMap {
    'image-gallery': HTMLImageGalleryElement;
  }
  interface ElementTagNameMap {
    'image-gallery': HTMLImageGalleryElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'image-gallery': JSXElements.ImageGalleryAttributes;
    }
  }
  namespace JSXElements {
    export interface ImageGalleryAttributes extends HTMLAttributes {
      'color'?: string;
      'src'?: Array<any>;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;