/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface ImgGallery {
      'color': string;
      'src': Array<any>;
    }
  }

  interface HTMLImgGalleryElement extends StencilComponents.ImgGallery, HTMLStencilElement {}

  var HTMLImgGalleryElement: {
    prototype: HTMLImgGalleryElement;
    new (): HTMLImgGalleryElement;
  };
  interface HTMLElementTagNameMap {
    'img-gallery': HTMLImgGalleryElement;
  }
  interface ElementTagNameMap {
    'img-gallery': HTMLImgGalleryElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'img-gallery': JSXElements.ImgGalleryAttributes;
    }
  }
  namespace JSXElements {
    export interface ImgGalleryAttributes extends HTMLAttributes {
      'color'?: string;
      'src'?: Array<any>;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;